version: '3.8'
services:
  postgres-test:
    image: postgres:15-alpine
    container_name: avito-testcase-postgres-test
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: avito_pr_test
    ports:
      - "55432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user -d avito_pr_test"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
  migrate-test:
    image: migrate/migrate:latest
    container_name: avito-testcase-migrate-test
    volumes:
      - ./migrations:/migrations
    command:
      - "-path=/migrations"
      - "-database=postgres://test_user:test_password@postgres-test:5432/avito_pr_test?sslmode=disable"
      - "up"
    depends_on:
      postgres-test:
        condition: service_healthy
volumes:
  postgres_test_data:

